name: FitnessTrackr Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  JWT_SECRET: TOPSECRET
  DATABASE_URL: postgresql://vincentpalomo:v2_3ysed_nbsdWVz5vhCJymkwPH3dqmN@db.bit.io:5432/vincentpalomo/fitness-dev?ssl=true

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: |
          npm install 
          npm run start:dev &
          npm test
