name: FitnessTrackr Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

env:
  JWT_SECRET: TOPSECRET

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: |
          npm install 
          npm run server:dev &
          npm test
